# -*- coding: utf-8 -*-
"""把 catalog_spider 生成的索引转成前端可用的 TS 数据文件。

读:
    catalog_spider/data/raw/program_tree.json         全量目录（拿 nameZh）
    catalog_spider/data/index/programs.json           索引（拿 trainType/department/major/...）
    catalog_spider/data/index/by_program_term.json    按学期分组的课程
写:
    src/data/curricula.ts  Record<programId, CurriculumRecord>

用法:
    uv run python scripts/curricula_to_ts.py
"""
from __future__ import annotations

import json
import os
import sys
from typing import Any, cast

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TREE_JSON = os.path.join(ROOT, "catalog_spider", "data", "raw", "program_tree.json")
PROGRAMS_JSON = os.path.join(ROOT, "catalog_spider", "data", "index", "programs.json")
BY_TERM_JSON = os.path.join(ROOT, "catalog_spider", "data", "index", "by_program_term.json")
OUT_TS = os.path.join(ROOT, "src", "data", "curricula.ts")


def _load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def main() -> int:
    if not os.path.exists(PROGRAMS_JSON) or not os.path.exists(BY_TERM_JSON):
        print("missing index files, run `uv run python -m catalog_spider build-index && build-by-term` first")
        return 1

    programs = cast(list[dict], _load_json(PROGRAMS_JSON))
    by_term = cast(dict[str, dict], _load_json(BY_TERM_JSON))

    # 从 program_tree 取每个 program 的 nameZh（programs.json 索引里没有 name）
    name_by_id: dict[str, str] = {}
    if os.path.exists(TREE_JSON):
        tree = cast(dict, _load_json(TREE_JSON))
        for dept in tree.values():
            for major in dept.get("majors", {}).values():
                for p in major.get("programs", []):
                    pid = p.get("id")
                    name = p.get("nameZh")
                    if pid is not None and name:
                        name_by_id[str(pid)] = name

    # join programs.json + name + by_term
    records: dict[str, dict] = {}
    for p in programs:
        pid = str(p["id"])
        records[pid] = {
            "id": p["id"],
            "name": name_by_id.get(pid, ""),
            "grade": p.get("grade"),
            "trainType": p.get("trainType"),
            "department": p.get("department"),
            "major": p.get("major"),
            "beginSemester": p.get("beginSemester"),
            "courseCount": p.get("courseCount", 0),
            "terms": by_term.get(pid, {}),
        }

    body = json.dumps(records, ensure_ascii=False, indent=2)

    header = """// AUTO-GENERATED by scripts/curricula_to_ts.py — do not edit by hand.
// 数据源: catalog_spider/data/raw/program_tree.json + catalog_spider/data/index/{programs,by_program_term}.json
// 匹配维度: program（培养方案），key = program id (string)
export interface CurriculumCourse {
  code: string;
  name: string;
  credits: number;
  compulsory: boolean;
  modulePath: string[];
}
export interface CurriculumRecord {
  id: number;
  name: string;
  grade: string;
  trainType: string;
  department: string;
  major: string;
  beginSemester: string | null;
  courseCount: number;
  terms: Record<string, CurriculumCourse[]>;
}
export const curricula: Record<string, CurriculumRecord> = """

    with open(OUT_TS, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(body)
        f.write(";\n")

    print(f"wrote {OUT_TS} ({len(records)} programs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())